using System.Reflection;
[assembly: AssemblyTitle("BuddhabrotCL")]
[assembly: AssemblyDescription("The Buddhabrot renderer with help of OpenCL")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("BuddhabrotCL")]
[assembly: AssemblyCopyright("Copyright © 2011-2017 Nikolai Voronin")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.8.4")]
